# debug docker compsoe
version: '3.1'

services:

  server:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_DATABASE=postgres
      - JWK=eyJleHBvcnRlZFByaXZhdGUiOnsia3R5IjoiUlNBIiwiYWxnIjoiUFMyNTYiLCJuIjoieEl2eS1VMms2ZFhpc1hXQm9TTWlpRWd1UURmMS1BYjFrY0xvVXd5NTVScjB5NklwRkhtV3JMS0g1T1VhTkJZS2N4UTYyejNmMHE3ME12R0FIS1g3VGlrZWtoWDhYaGI1M0pHV2ZMLUJpTExnWU9RbThYMElJR19EZDF6ZmluaWI0eFhIT0RWSmg2d1BfSDJBcWkwaDdEWDJoSTN6SmFWb0JWSkd6ODZjem4yUkFZSVJHTGVOdmhXdl9LVHN5WGdKSWd5NUdkdXNVckszc3ZaYjJmLWNzbFhyWC0xcl9WdS0tT3cyLXhoM08xYmdTQklXSGgyYy00czhWTVhxOU1PbnVFRTZXbzg2YWtjZzNUa24xTjVYb3d4azlzSGFIdk03ZDVOV0NKbE8wWnEtaXFQRmdjWUlSREM3SlNKc2pQUTVyMlJHaXBWd1pSdlBCN2dGRnlDeVhRIiwiZSI6IkFRQUIiLCJkIjoiZnl4aW9lY1lidWtqRGxvTzcxbVJqWWJPem1Tbk5iNGpCUmFOUnJkMFRRYTlJRW1qdFFqYmNwRHVGekFhWFZ0cGxYNmdlcDIxaGxnSDBES3RCMXhxbC05SlJaTU9RVDh5bXdKazBnRUQ2cFI3VkpZcmtKT3JQM214aXprX3R4UkZJWkZFMzF5ellDTDRFUktQdncwRzV4VWZsak5YQWFQZUE1dHlFQ0lMR2h2SHY4OG9sOFQ4WW5mbk1ySExoODZ3RWpUNnE1eklMUFdVSG9XNk9WZzBPUjBPZFV1bzlKU2V2N0ZjLW5nQXBQVU9UNFdCOHl0TXdqZjc2akhWb3lUY2F0eTI3a0RLTjUyTDlJNnQ4MTVObW4ta0J2LWpELTF2WTJfYVBxZmhmblIyNU03clZPMmJDWHBpbGFVQzhJZEFUSFNjWTB2OGtQLVkwckNZX1lZaURRIiwicCI6InpHdEJUUC1vcjI0WTVpemJ2NDJZTGxOMHBURlNDbE5TUVk4bXM2Tk43eTVPOUY3TkRpdHhZTU8yTWs1RllQaS1tV1lPUFFDMGdvaGp0RXhMeGNzRl85WWNZSmo3MTZLSU9NVkw5SG9KUWwxcGxvQXFYYUlRWTRrRGpSRzFVMVhYUzNVRjRaUV80OGFtb3h4REUtSG1TSmUwSWFDa3Y2Ykppb0lzNVhCUnliYyIsInEiOiI5aVFzQWg5cFhNcVpBUjZJWjNPSTAySFJrenROY0Z6YkJsRERoakhRUlI4ZzlQTWVyTExDejdubDZMQV9adzNLY1dSaEx3WVFXbnpJOTNVWE9zTi1xd3JiV2VGTzJja2hMNWhvb1dwZXdHWVF2TTZnS3NxYWoyOGMwdXFaTWQ1MF9ZTUNQakdfc0FxdXVGcUxNdVFwM3IzalNfMzJkbTZTUDhaYXVndzVOSXMiLCJkcCI6ImxabWd6cE1EaG0tU2RWRTYtUExNX29wQkFXd1kyRW1tRnlpR2NFMEJDaHZmMkdOUXVoXzg5NDREVnNtRmFMUmgtSzJCbWc5Y0MzTjVWRWZKNUZUeWJRcnE5WjdBSUUxb1ZfTzc1STB6SFloemI1c1laakhtd0pGVE1maFZ0VWxMS0lQWjZfNnN5eXRrWkZhWW1JSm9INVEyVmEzVkpCVVJ4ZllDbVY4YjJfMCIsImRxIjoiczhRSFFDV2cxZHhCa3NleDU1eEJ1ZUFmSi1DUDFoaDZfa25PQXh3dWQ4MGNUTW1qQlk0cEtYMGpwS1hVS0hleC1zN05DNExxUHF3VU9tYVI2S0VPeWV6TDl3RE9qZENQSkN1emZ2QW84MnVYbmMxcXZOWHJ2QVh5anpnM1dteVdGUEN4bXFyS3pNLUFlN1BsSmUzdGhuZzRvUy1CNlUwb0V0dlROejNtS2JFIiwicWkiOiJ2M1RUSnIyVzNvOVFuQzZFMnliOGFaU3QwQlVpUkswQkhmOThIWUo5VUtKS1F2Xzc0ZG9lanBucDNZSl9KRk9DOUxpRURJRUdzNTVhbWRualY1elJIV1U1VkczektYbl9nU1FvU3J0VXVuZDNYU3JFRjU2YktaRVFDVTFVQlBVZXFxR0p4N1lWYk5xUWw3MXFZYkZFU19LZC10SlJ4ejVTNTBhNHlGQklCRWMiLCJrZXlfb3BzIjpbInNpZ24iXSwiZXh0IjpmYWxzZX0sImV4cG9ydGVkUHVibGljIjp7Imt0eSI6IlJTQSIsImFsZyI6IlBTMjU2IiwibiI6InhJdnktVTJrNmRYaXNYV0JvU01paUVndVFEZjEtQWIxa2NMb1V3eTU1UnIweTZJcEZIbVdyTEtINU9VYU5CWUtjeFE2MnozZjBxNzBNdkdBSEtYN1Rpa2VraFg4WGhiNTNKR1dmTC1CaUxMZ1lPUW04WDBJSUdfRGQxemZpbmliNHhYSE9EVkpoNndQX0gyQXFpMGg3RFgyaEkzekphVm9CVkpHejg2Y3puMlJBWUlSR0xlTnZoV3ZfS1RzeVhnSklneTVHZHVzVXJLM3N2WmIyZi1jc2xYclgtMXJfVnUtLU93Mi14aDNPMWJnU0JJV0hoMmMtNHM4Vk1YcTlNT251RUU2V284NmFrY2czVGtuMU41WG93eGs5c0hhSHZNN2Q1TldDSmxPMFpxLWlxUEZnY1lJUkRDN0pTSnNqUFE1cjJSR2lwVndaUnZQQjdnRkZ5Q3lYUSIsImUiOiJBUUFCIiwia2V5X29wcyI6WyJ2ZXJpZnkiXSwiZXh0Ijp0cnVlfX0=
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # debug, remove when done
    ports:
      - "5432:5432"

  # explore database, for debug only
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data: null
